name: Publish to PyPI

on:
  push:
    branches:
      - main 

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true  # Clean the working directory
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'
      - run: pip install build twine
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@v1.7.1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}